Revamp colab
rom1504/dalle-service pull request #7
Opened 2021-07-14 03:31 UTC by johnpaulbin

2021-07-14 10:32 UTC, rom1504 approved these changes

2021-07-14 10:33 UTC, rom1504 requested changes

2021-07-14 10:33 UTC, rom1504 commented on dalle_back.ipynb
> +        "<a href=\"https://colab.research.google.com/github/johnpaulbin/dalle-service/blob/master/dalle_back.ipynb\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge
could you make this link to this repo ?

2021-07-15 00:50 UTC, johnpaulbin commented
Okay, updated

2021-07-15 07:44 UTC, rom1504 approved these changes

2021-07-15 07:44 UTC, merged